- name: docker build and push
  hosts: local  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Build Docker Image
      command: docker build -t demo .
      args:
        chdir: /var/lib/jenkins/workspace/demo

    - name: tag image
      command: docker tag demo:latest  
    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 demo:latest
